---
title: "Chapter 01: Introduction to Machine Learning"
output: html_notebook
---


## The data sets

* Ames homes sales data
    
```{r import-ames-data}
# access data
ames <- AmesHousing::make_ames()

# initial dimension
dim(ames)

# response variable
head(ames$Sale_Price)
```


```{r}
glimpse(ames)
```


```{r}
library(tidyverse)
ggplot(ames, aes(Lot_Shape)) +
  geom_bar()
```


```{r}
ames %>% 
 # filter(Lot_Area < 25000) %>% 
 ggplot(aes(Lot_Area, Sale_Price)) +
 geom_point()

```


```{r}
ggplot(ames, aes(Sale_Price)) +
  geom_density()

```



    
* Employee attrition information originally provided by [IBM Watson Analytics Lab](https://www.ibm.com/communities/analytics/watson-analytics-blog/hr-employee-attrition/).


```{r import-attrition-data}
# access data
# attrition <- rsample::attrition
library(modeldata)
data(attrition)

# initial dimension
dim(attrition)

# response variable
head(attrition$Attrition)
```    
    
* MNIST handwritten numbers data 

```{r import-mnist-data, message=FALSE, warning=FALSE}
#access data
mnist <- dslabs::read_mnist()
names(mnist)

# initial feature dimensions
dim(mnist$train$images)

# response variable
head(mnist$train$labels)
```   

* Grocery items and quantities purchased. 

```{r import-mybasket-data, message=FALSE, warning=FALSE}
# URL to download/read in the data
url <- "https://koalaverse.github.io/homlr/data/my_basket.csv"

# Access data
my_basket <- readr::read_csv(url)

# Print dimensions
dim(my_basket)

# Peek at response variable
my_basket
```   
